### ISSUE TITLE
Use $colorMode.preference instead $colorMode.value

### ISSUE THREAD

**Issue by xdiegom** [fayazara/nuxt-tailwind-darkmode#1]
Hi Fayaz,

Nice implementation. 

Just one quick change on the toggle method.

Instead of updating `this.$colorMode.value`, use `this.colorMode.preference` in `toggle` method:

```
toggle() {
    this.$colorMode.preference = this.$colorMode.value == "light" ? "dark" : "light";
}
```

This is based on docs recommendation: https://github.com/nuxt-community/color-mode-module#usage:

- `preference`: Actual color-mode selected (can be 'system'), **update it to change the user prefered color mode**

- `value`: Useful to know what color mode has been detected when $colorMode === 'system', **you should not update it**

**Comment by fayazara** [comment]
Fixed in https://github.com/fayazara/nuxt-tailwind-darkmode/commit/582773e3666459a883f0eed12c6fcfb0b1655c10.

Thanks for the heads up!
